# ESLint Configuration for CERES Frontend

root: true
env:
  browser: true
  es2020: true
  node: true
extends:
  - eslint:recommended
  - '@typescript-eslint/recommended'
  - plugin:react-hooks/recommended
ignorePatterns:
  - dist
  - .eslintrc.cjs
  - node_modules
  - build
  - coverage
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react-refresh
  - '@typescript-eslint'
rules:
  # Disable strict rules that cause warnings
  react-refresh/only-export-components: off
  '@typescript-eslint/no-unused-vars': 
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  no-unused-vars:
    - warn  
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  react-hooks/exhaustive-deps: warn
  # Allow console for development
  no-console: warn
  # Allow any for rapid development
  '@typescript-eslint/no-explicit-any': warn

