root: true
env:
  browser: true
  es2020: true
  node: true
extends:
  - eslint:recommended
  - '@typescript-eslint/recommended'
  - plugin:react-hooks/recommended
ignorePatterns:
  - dist
  - .eslintrc.cjs
  - node_modules
  - build
  - coverage
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react-refresh
  - '@typescript-eslint'
rules:
  # Make all rules warnings instead of errors
  react-refresh/only-export-components: warn
  '@typescript-eslint/no-unused-vars': 
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_|^[A-Z_]'
  no-unused-vars:
    - warn  
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_|^[A-Z_]'
  react-hooks/exhaustive-deps: warn
  no-console: warn
  '@typescript-eslint/no-explicit-any': warn
  # Allow unused variables that start with underscore or are uppercase
  no-undef: warn

