# Railway.app deployment configuration
[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_INSTALL_PHASE_COMMANDS = "apt-get update && apt-get install -y libpq-dev python3-dev gcc tesseract-ocr libmagic1"

[deploy.env]
DJANGO_ENVIRONMENT = "production"
DEBUG = "False"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

