# Railway.app deployment configuration
[build]
builder = "NIXPACKS"

[build.env]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_INSTALL_PHASE_COMMANDS = "apt-get update && apt-get install -y libpq-dev python3-dev gcc g++ tesseract-ocr libmagic1 libgl1-mesa-glx libglib2.0-0 libsm6 libxext6 libxrender-dev libgomp1 libfontconfig1"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.env]
DJANGO_ENVIRONMENT = "production"
DEBUG = "False"
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

