name: Feature Request
description: Sugerir uma nova funcionalidade para o CERES
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova funcionalidade! Por favor, preencha as informações abaixo.

  - type: textarea
    id: summary
    attributes:
      label: Resumo da Funcionalidade
      description: Descreva brevemente a funcionalidade que você gostaria de ver
      placeholder: Ex. Adicionar suporte para verificação de sanções em tempo real...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problema que Resolve
      description: Que problema esta funcionalidade resolveria?
      placeholder: Ex. Atualmente, o sistema só verifica sanções manualmente, o que é lento...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução Proposta
      description: Descreva como você imagina que esta funcionalidade funcionaria
      placeholder: Ex. Um sistema de monitoramento contínuo que verifica automaticamente...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Casos de Uso
      description: Descreva cenários específicos onde esta funcionalidade seria útil
      placeholder: |
        1. Quando um novo cliente é cadastrado...
        2. Durante auditorias regulares...
        3. Para compliance em tempo real...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Qual a importância desta funcionalidade para você?
      options:
        - Baixa (seria bom ter)
        - Média (melhoraria significativamente o workflow)
        - Alta (funcionalidade essencial)
        - Crítica (bloqueador para adoção)
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Categoria
      description: Em qual módulo esta funcionalidade se encaixaria?
      options:
        - Dashboard
        - Cadastro de Clientes
        - Processamento de Documentos
        - Screening de Sanções
        - Relatórios
        - API
        - Segurança
        - Performance
        - UI/UX
        - Integração
        - Outro
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas Consideradas
      description: Você considerou outras formas de resolver este problema?
      placeholder: Ex. Tentei usar a API X, mas não atende porque...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups ou Exemplos
      description: Se aplicável, adicione mockups, wireframes ou exemplos de outras ferramentas

  - type: dropdown
    id: complexity
    attributes:
      label: Complexidade Estimada
      description: Na sua opinião, qual a complexidade desta funcionalidade?
      options:
        - Simples (mudança pequena)
        - Média (nova funcionalidade)
        - Complexa (mudança significativa)
        - Muito complexa (requer arquitetura nova)

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Critérios de Aceitação
      description: Como você saberia que esta funcionalidade foi implementada corretamente?
      placeholder: |
        - [ ] O sistema deve permitir...
        - [ ] O usuário deve conseguir...
        - [ ] A performance deve ser...

  - type: dropdown
    id: users-affected
    attributes:
      label: Usuários Afetados
      description: Que tipo de usuários se beneficiariam desta funcionalidade?
      options:
        - Todos os usuários
        - Administradores
        - Analistas de compliance
        - Auditores
        - Desenvolvedores (API)
        - Usuários finais
      multiple: true

  - type: textarea
    id: business-impact
    attributes:
      label: Impacto no Negócio
      description: Como esta funcionalidade impactaria positivamente o negócio?
      placeholder: Ex. Reduziria o tempo de análise em 50%, melhoraria a conformidade...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Por favor, confirme que você verificou os itens abaixo
      options:
        - label: Eu verifiquei que esta funcionalidade não foi sugerida anteriormente
          required: true
        - label: Eu considerei se esta funcionalidade se alinha com os objetivos do CERES
          required: true
        - label: Eu incluí informações suficientes para entender a proposta
          required: true

